// import { Inter } from "next/font/google";

import axios from "axios";

// import ArrowGotoUp from "@/components/ArrowGoToUp";
// import Footer from "@/components/Footer";
// import Header from "@/components/Header";

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Thể loại",
  description: "Generated by create next app",
};

// export async function generateMetadata({ params }) {
//   const nameCategory = params.nameCategory;

//   return {
//     title: nameCategory,
//     // description: movie.desc,
//   };
// }

export async function generateStaticParams() {
  const categoriesResponse = await axios.get(
    `${process.env.NEXT_PUBLIC_URL}/api/v1/category`
  );

  if (!categoriesResponse && !categoriesResponse?.data?.data) return [];

  const dataCategories = categoriesResponse?.data?.data;
  // console.log(dataCategories);

  return dataCategories.map((cate) => ({
    nameCategory: cate.slug,
  }));
}

export default function RootLayout({ children }) {
  return <main>{children}</main>;
}
