// import { Inter } from "next/font/google";

// import ArrowGotoUp from "@/components/ArrowGoToUp";
// import Footer from "@/components/Footer";
// import Header from "@/components/Header";

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "trang ca nhan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <main>{children}</main>;
}
